<?php

return array(
	'dbcache.enabled' => true,
	'dbcache.debug' => false,
	'dbcache.engine' => 'file',
	'dbcache.file.gc' => 3600,
	'dbcache.memcached.engine' => 'auto',
	'dbcache.memcached.servers' => array(
		'localhost:11211',
	),
	'dbcache.reject.logged' => true,
	'dbcache.reject.uri' => array(
	),
	'dbcache.reject.cookie' => array(
	),
	'dbcache.reject.sql' => array(
		'gdsr_',
	),
	'dbcache.lifetime' => 180,
	'pgcache.enabled' => true,
	'pgcache.debug' => false,
	'pgcache.engine' => 'file',
	'pgcache.file.gc' => 3600,
	'pgcache.memcached.engine' => 'auto',
	'pgcache.memcached.servers' => array(
		'localhost:11211',
	),
	'pgcache.lifetime' => 3600,
	'pgcache.compression' => 'gzip',
	'pgcache.cache.query' => true,
	'pgcache.cache.home' => true,
	'pgcache.cache.feed' => true,
	'pgcache.cache.404' => false,
	'pgcache.cache.flush' => false,
	'pgcache.cache.headers' => array(
		'Last-Modified',
		'Content-Type',
		'X-Pingback',
	),
	'pgcache.accept.files' => array(
		'wp-comments-popup.php',
		'wp-links-opml.php',
		'wp-locations.php',
	),
	'pgcache.reject.logged' => true,
	'pgcache.reject.uri' => array(
		'wp-.*\\.php',
		'index\\.php',
	),
	'pgcache.reject.ua' => array(
		'bot',
		'ia_archive',
		'slurp',
		'crawl',
		'spider',
	),
	'pgcache.reject.cookie' => array(
	),
	'pgcache.mobile.redirect' => '',
	'pgcache.mobile.agents' => array(
		'2.0 MMP',
		'240x320',
		'ASUS',
		'AU-MIC',
		'Alcatel',
		'Amoi',
		'Android',
		'Audiovox',
		'AvantGo',
		'BenQ',
		'Bird',
		'BlackBerry',
		'Blazer',
		'CDM',
		'Cellphone',
		'DDIPOCKET',
		'Danger',
		'DoCoMo',
		'Elaine/3.0',
		'Ericsson',
		'EudoraWeb',
		'Fly',
		'HP.iPAQ',
		'Haier',
		'Huawei',
		'IEMobile',
		'J-PHONE',
		'KDDI',
		'KONKA',
		'KWC',
		'KYOCERA/WX310K',
		'LG',
		'LG/U990',
		'Lenovo',
		'MIDP-2.0',
		'MMEF20',
		'MOT-V',
		'MobilePhone',
		'Motorola',
		'NEWGEN',
		'NetFront',
		'Newt',
		'Nintendo Wii',
		'Nitro',
		'Nokia',
		'Novarra',
		'O2',
		'Opera Mini',
		'Opera.Mobi',
		'PANTECH',
		'PDXGW',
		'PG',
		'PPC',
		'PT',
		'Palm',
		'Panasonic',
		'Philips',
		'Playstation Portable',
		'ProxiNet',
		'Proxinet',
		'Qtek',
		'SCH',
		'SEC',
		'SGH',
		'SHARP-TQ-GX10',
		'SIE',
		'SPH',
		'Sagem',
		'Samsung',
		'Sanyo',
		'Sendo',
		'Sharp',
		'Small',
		'Smartphone',
		'SoftBank',
		'SonyEricsson',
		'Symbian',
		'Symbian OS',
		'SymbianOS',
		'TS21i-10',
		'Toshiba',
		'Treo',
		'UP.Browser',
		'UP.Link',
		'UTS',
		'Vertu',
		'WILLCOME',
		'WinWAP',
		'Windows CE',
		'Windows.CE',
		'Xda',
		'ZTE',
		'dopod',
		'hiptop',
		'htc',
		'i-mobile',
		'iPhone',
		'iPod',
		'nokia',
		'portalmmm',
		'vodafone',
	),
	'minify.enabled' => true,
	'minify.debug' => false,
	'minify.engine' => 'file',
	'minify.file.locking' => true,
	'minify.file.gc' => 86400,
	'minify.memcached.engine' => 'auto',
	'minify.memcached.servers' => array(
		'localhost:11211',
	),
	'minify.rewrite' => true,
	'minify.fixtime' => 0,
	'minify.compress' => true,
	'minify.compress.ie6' => true,
	'minify.options' => array(
		'bubbleCssImports' => false,
		'minApp' => array(
			'groupsOnly' => false,
			'maxFiles' => 20,
		),
	),
	'minify.symlinks' => array(
	),
	'minify.maxage' => 86400,
	'minify.lifetime' => 86400,
	'minify.upload' => true,
	'minify.html.enable' => true,
	'minify.html.reject.admin' => true,
	'minify.html.inline.css' => false,
	'minify.html.inline.js' => false,
	'minify.html.strip.crlf' => false,
	'minify.css.enable' => true,
	'minify.css.strip.comments' => false,
	'minify.css.strip.crlf' => false,
	'minify.css.groups' => array(
	),
	'minify.js.enable' => true,
	'minify.js.combine.header' => false,
	'minify.js.combine.footer' => false,
	'minify.js.strip.comments' => false,
	'minify.js.strip.crlf' => false,
	'minify.js.groups' => array(
	),
	'minify.reject.ua' => array(
	),
	'minify.reject.uri' => array(
	),
	'cdn.enabled' => false,
	'cdn.debug' => false,
	'cdn.engine' => 's3',
	'cdn.includes.enable' => true,
	'cdn.includes.files' => 'wlwmanifest.xml;*.css;*.js;*.gif;*.png;*.jpg',
	'cdn.theme.enable' => true,
	'cdn.theme.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.ico',
	'cdn.minify.enable' => true,
	'cdn.custom.enable' => true,
	'cdn.custom.files' => array(
		'favicon.ico',
	),
	'cdn.import.external' => false,
	'cdn.import.files' => '*.jpg;*.png;*.gif;*.avi;*.wmv;*.mpg;*.wav;*.mp3;*.txt;*.rtf;*.doc;*.xls;*.rar;*.zip;*.tar;*.gz;*.exe',
	'cdn.limit.queue' => 25,
	'cdn.mirror.domain' => '',
	'cdn.ftp.host' => '',
	'cdn.ftp.user' => '',
	'cdn.ftp.pass' => '',
	'cdn.ftp.path' => '',
	'cdn.ftp.pasv' => false,
	'cdn.ftp.domain' => '',
	'cdn.s3.key' => '',
	'cdn.s3.secret' => '',
	'cdn.s3.bucket' => '',
	'cdn.cf.key' => '',
	'cdn.cf.secret' => '',
	'cdn.cf.bucket' => '',
	'cdn.cf.id' => '',
	'cdn.cf.cname' => '',
	'cdn.reject.ua' => array(
	),
	'cdn.reject.uri' => array(
	),
	'cdn.reject.files' => array(
		'wp-content/uploads/wpcf7_captcha/*',
	),
	'common.support' => '',
	'common.install' => 1263152119,
	'common.tweeted' => 0,
	'common.widget.latest' => true,
	'notes.defaults' => true,
	'notes.wp_content_perms' => true,
	'notes.cdn_first_time' => true,
	'notes.php_is_old' => true,
	'notes.theme_changed' => false,
	'notes.wp_upgraded' => false,
	'notes.plugins_updated' => true,
	'notes.cdn_upload' => true,
	'notes.need_empty_pgcache' => false,
	'notes.need_empty_minify' => false,
	'notes.pgcache_rules_core' => true,
	'notes.pgcache_rules_cache' => true,
	'notes.minify_rules' => true,
	'notes.support_us' => false,
	'notes.no_curl' => true,
	'notes.no_zlib' => true,
	'notes.zlib_output_compression' => true,
);